version: '3.1'
services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fooddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
volumes:
  postgres-data: